[project]
name = "pet-adoption-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "elasticsearch==8.15.1",
    "pandas>=2.3.3",
    "pandas-stubs>=2.3.2.250926",
    "streamlit>=1.50.0",
]
